[[libstdcxx]]
arch = "x86_64"
git-tree-sha1 = "171aaff062474d3b92973403e18bbf9ebb7af95e"
libc = "glibc"
os = "linux"

    [[libstdcxx.download]]
    sha256 = "d3560ce1e056aa751cc0bfa961258711dcc78dcd9c85f63ffd98dc7be4633de4"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/libstdcxx-v14.2.0-x86_64-linux-gnu.tar.gz"
[[libstdcxx]]
arch = "i686"
git-tree-sha1 = "a70fa68efbe43f41635abddc496f5dfb61ebaacf"
libc = "glibc"
os = "linux"

    [[libstdcxx.download]]
    sha256 = "28ecb21a977febde837a17e1365ee669d4b4874f86d95e8cdf7faafa3c734069"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/libstdcxx-v14.2.0-i686-linux-gnu.tar.gz"
[[libstdcxx]]
arch = "aarch64"
git-tree-sha1 = "49d2913044eb1c75f7f4cb1c5e99053cbd89ea54"
libc = "glibc"
os = "linux"

    [[libstdcxx.download]]
    sha256 = "f5a7026057981ed696462a233416ed2f01b63d16649bbe071e8cc93c3def3002"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/libstdcxx-v14.2.0-aarch64-linux-gnu.tar.gz"
[[libstdcxx]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7f8e2032ee851ce0d75b82398c470ebe45ffb0ed"
libc = "glibc"
os = "linux"

    [[libstdcxx.download]]
    sha256 = "64a1d485895a7c119a1d2e42432bb41524cac9a417d3b9c64d240de85214415e"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/libstdcxx-v14.2.0-armv6l-linux-gnueabihf.tar.gz"
[[libstdcxx]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "74b4f5908b5b3f31dcf15c2f8620182b30f8ad51"
libc = "glibc"
os = "linux"

    [[libstdcxx.download]]
    sha256 = "a20ae92d76f59bfe73bb35b5a3389ed6ddd74991c7d2b863ee5934682708d7d5"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/libstdcxx-v14.2.0-armv7l-linux-gnueabihf.tar.gz"
[[libstdcxx]]
arch = "powerpc64le"
git-tree-sha1 = "37ba8214c8d8463b9e6ec966bfaa3020aca09c59"
libc = "glibc"
os = "linux"

    [[libstdcxx.download]]
    sha256 = "75e991194ce71bb0242774b5d259ea93ce9ca230e76571af14a80dbf797aaa8f"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/libstdcxx-v14.2.0-powerpc64le-linux-gnu.tar.gz"
[[libstdcxx]]
arch = "x86_64"
git-tree-sha1 = "e76e9419624179d31ea57f0a552ffd8e9026c3ec"
libc = "musl"
os = "linux"

    [[libstdcxx.download]]
    sha256 = "4f03c99b69b6f483b5c5b83114f4b1a3be29a644707eebff9934e582ffe12ed2"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/libstdcxx-v14.2.0-x86_64-linux-musl.tar.gz"
[[libstdcxx]]
arch = "i686"
git-tree-sha1 = "fdf5e4b3d5e9e9edf2fc963284282d37e4d92f86"
libc = "musl"
os = "linux"

    [[libstdcxx.download]]
    sha256 = "56101ca13018551fa80a0b864c4f8452375c459d38889a4638b93e40f5db8432"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/libstdcxx-v14.2.0-i686-linux-musl.tar.gz"
[[libstdcxx]]
arch = "aarch64"
git-tree-sha1 = "bafc9a8c4bf92376df4b644e0b169a4fc91122ec"
libc = "musl"
os = "linux"

    [[libstdcxx.download]]
    sha256 = "b77b36e60e7d6337258b2c99370e4a1a6326e08eda68db49fea6f28d3d8f8156"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/libstdcxx-v14.2.0-aarch64-linux-musl.tar.gz"
[[libstdcxx]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "196da2ca2c4fab2796a361e91a7916c012704106"
libc = "musl"
os = "linux"

    [[libstdcxx.download]]
    sha256 = "4e48dcb08cf04e3f7ec7adc64c4eb3d189e3149356bb55fb9eb0c79a740bb6d5"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/libstdcxx-v14.2.0-armv6l-linux-musleabihf.tar.gz"
[[libstdcxx]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7dc318533f4209d64fe16cfb023f787f6418077d"
libc = "musl"
os = "linux"

    [[libstdcxx.download]]
    sha256 = "8cad0edb155615025d2952a06e4d30983fe7c09a2f8fcd30ae4941129d980c82"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/libstdcxx-v14.2.0-armv7l-linux-musleabihf.tar.gz"
[[libstdcxx]]
arch = "x86_64"
git-tree-sha1 = "b08656311e61c836d13bdcda003180a30bbaa6d9"
os = "windows"

    [[libstdcxx.download]]
    sha256 = "489d0972123028e1e8107c8158e1c93f5b85a5ccbbf96e2fe4251b53de808738"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/libstdcxx-v14.2.0-x86_64-w64-mingw32.tar.gz"
[[libstdcxx]]
arch = "i686"
git-tree-sha1 = "d42cf80a06fedc9f98099a863f84a4fce80d7e40"
os = "windows"

    [[libstdcxx.download]]
    sha256 = "ae0a9b46780c7a4abc424d8868ad9fc35acb2694b43124af5de18f7d24e4b7d2"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/libstdcxx-v14.2.0-i686-w64-mingw32.tar.gz"
[[libstdcxx]]
arch = "x86_64"
git-tree-sha1 = "be5ee25a892a73e97a5471dc61f945f140676d65"
os = "macos"

    [[libstdcxx.download]]
    sha256 = "5faf8011fe94186a6461ff1a43e4f9132d04a799e490b46eee2628c4ef65420c"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/libstdcxx-v14.2.0-x86_64-apple-darwin.tar.gz"
[[libstdcxx]]
arch = "aarch64"
git-tree-sha1 = "c8d8a85c501e0d7af18058f8a700d7b3915e2e36"
os = "macos"

    [[libstdcxx.download]]
    sha256 = "ada3b47eeb62a602b8165983de53239c90859459af51396034e9c2f653c4277d"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/libstdcxx-v14.2.0-aarch64-apple-darwin.tar.gz"

[[libstdcxx-build_log]]
arch = "x86_64"
git-tree-sha1 = "9537d197d6b5d61a7ddf06049280e7538f838227"
lazy = true
libc = "glibc"
os = "linux"

    [[libstdcxx-build_log.download]]
    sha256 = "05df7f1c3ad0be89a5c5b917642b4b3d1e85dddc444a76be96ccae272d6ee42f"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/libstdcxx-build_log-v14.2.0-x86_64-linux-gnu.tar.gz"
[[libstdcxx-build_log]]
arch = "i686"
git-tree-sha1 = "467cf6256d5cb40c40fef2c5c23ea70256d2db92"
lazy = true
libc = "glibc"
os = "linux"

    [[libstdcxx-build_log.download]]
    sha256 = "746f3751b15b30b5211ad1c8f3c8808988f44ff266b1f9f4d5a2bdd758409535"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/libstdcxx-build_log-v14.2.0-i686-linux-gnu.tar.gz"
[[libstdcxx-build_log]]
arch = "aarch64"
git-tree-sha1 = "9795602333a245a25986cfb31dc722d22604b412"
lazy = true
libc = "glibc"
os = "linux"

    [[libstdcxx-build_log.download]]
    sha256 = "8101ec8a1dde16b43b28450b089aa66da53a822eabe4c6ed1e72a69c5b3e8757"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/libstdcxx-build_log-v14.2.0-aarch64-linux-gnu.tar.gz"
[[libstdcxx-build_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "4dfc132510810201954fa64898cd5c9bd61fe353"
lazy = true
libc = "glibc"
os = "linux"

    [[libstdcxx-build_log.download]]
    sha256 = "5f5f5af0343f6a0b24287623868b46c986f1af3dc2aa8f20c1e737bf38a3be05"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/libstdcxx-build_log-v14.2.0-armv6l-linux-gnueabihf.tar.gz"
[[libstdcxx-build_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ab83ef460184148e5394bbd3f15997c5f5b0cc44"
lazy = true
libc = "glibc"
os = "linux"

    [[libstdcxx-build_log.download]]
    sha256 = "682d95140cf2ced92fd5751e0a85d98e05d89cda833c7912b963cd4015f05fc7"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/libstdcxx-build_log-v14.2.0-armv7l-linux-gnueabihf.tar.gz"
[[libstdcxx-build_log]]
arch = "powerpc64le"
git-tree-sha1 = "77f455ec8e59988c3349b64b2d0fb538834114dd"
lazy = true
libc = "glibc"
os = "linux"

    [[libstdcxx-build_log.download]]
    sha256 = "6b3d970f2d50a26a4a6fcdac9bac5ad31c4ca174d27e4b2ee6739fa6b859ce41"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/libstdcxx-build_log-v14.2.0-powerpc64le-linux-gnu.tar.gz"
[[libstdcxx-build_log]]
arch = "x86_64"
git-tree-sha1 = "11bd5131e8ff515f7dd7e5b4538fdefa92a7e536"
lazy = true
libc = "musl"
os = "linux"

    [[libstdcxx-build_log.download]]
    sha256 = "198d3355eb894fdbc24161019092e991fa7099b314ed24adece8f4cec647dbdc"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/libstdcxx-build_log-v14.2.0-x86_64-linux-musl.tar.gz"
[[libstdcxx-build_log]]
arch = "i686"
git-tree-sha1 = "00fbe4db2283d379627bb33903a116fba1195b87"
lazy = true
libc = "musl"
os = "linux"

    [[libstdcxx-build_log.download]]
    sha256 = "eaaaca7d229ebf379f206437bccdadaac134723592c2a8b6f4fff0c5aff15ccd"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/libstdcxx-build_log-v14.2.0-i686-linux-musl.tar.gz"
[[libstdcxx-build_log]]
arch = "aarch64"
git-tree-sha1 = "0551a733b51b86741e6b97b300c884db4cca943d"
lazy = true
libc = "musl"
os = "linux"

    [[libstdcxx-build_log.download]]
    sha256 = "bea4e0cf1ef1379c415b94f1137f10184c81daf3d874551a7c628c3f16c6d79b"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/libstdcxx-build_log-v14.2.0-aarch64-linux-musl.tar.gz"
[[libstdcxx-build_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "798c97e5f6961728cfb2bfbef15c39ca935aaff7"
lazy = true
libc = "musl"
os = "linux"

    [[libstdcxx-build_log.download]]
    sha256 = "aa811a98ac86326e7ae2208f309f4da94779c7bdc5197588fc99acba5f30e6de"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/libstdcxx-build_log-v14.2.0-armv6l-linux-musleabihf.tar.gz"
[[libstdcxx-build_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "fb392a3b71b879c5289083097b930f7e1df87caa"
lazy = true
libc = "musl"
os = "linux"

    [[libstdcxx-build_log.download]]
    sha256 = "279de9b6c25863b773c882403e96bd8d6fdd0e0d2f8e8200f818df7489ee9138"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/libstdcxx-build_log-v14.2.0-armv7l-linux-musleabihf.tar.gz"
[[libstdcxx-build_log]]
arch = "x86_64"
git-tree-sha1 = "db1ff8fab727f683d5f8ae790add68af3fe69c6f"
lazy = true
os = "windows"

    [[libstdcxx-build_log.download]]
    sha256 = "8e7e7bd2028a09f9e3e6633df5997b34331473dc6b947104c497ce41fb5189e4"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/libstdcxx-build_log-v14.2.0-x86_64-w64-mingw32.tar.gz"
[[libstdcxx-build_log]]
arch = "i686"
git-tree-sha1 = "e9b38a7019c7254abe63831616d4fc60c059da4f"
lazy = true
os = "windows"

    [[libstdcxx-build_log.download]]
    sha256 = "bd8230f884bbaa2c91c35f97f75c328cf612c09047b9832d1b6cf9089c861944"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/libstdcxx-build_log-v14.2.0-i686-w64-mingw32.tar.gz"
[[libstdcxx-build_log]]
arch = "x86_64"
git-tree-sha1 = "fa428d4a2d1811e06d1bd003819fc3fa88ee516b"
lazy = true
os = "macos"

    [[libstdcxx-build_log.download]]
    sha256 = "a12c50f54bbed27788f75f840daabcb1cdbbb5f0d9b6a4f2870340c48d96ddae"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/libstdcxx-build_log-v14.2.0-x86_64-apple-darwin.tar.gz"
[[libstdcxx-build_log]]
arch = "aarch64"
git-tree-sha1 = "f694ee072249013aa3b9b413504b80f031e06d10"
lazy = true
os = "macos"

    [[libstdcxx-build_log.download]]
    sha256 = "8029ef6cb44b57fb3e5232c4086ea8099f337d2fee1903e9f10a0fa4edf7bd42"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/libstdcxx-build_log-v14.2.0-aarch64-apple-darwin.tar.gz"

[[libstdcxx-extract_log]]
arch = "x86_64"
git-tree-sha1 = "4aec90e043e3c512205577e56ff1511a914cc4a8"
lazy = true
libc = "glibc"
os = "linux"

    [[libstdcxx-extract_log.download]]
    sha256 = "67227707842878257c9bcbf0fa806c9027d2732a85a465bc25c90cef871282c7"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/libstdcxx-extract_log-v14.2.0-x86_64-linux-gnu.tar.gz"
[[libstdcxx-extract_log]]
arch = "i686"
git-tree-sha1 = "cdc21df29d34e12f5d43b5cb85e4ec4455cf8e7c"
lazy = true
libc = "glibc"
os = "linux"

    [[libstdcxx-extract_log.download]]
    sha256 = "170584601bfa241bf2aac11d6654fbc99959c253d95b15da842c926ae25e644e"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/libstdcxx-extract_log-v14.2.0-i686-linux-gnu.tar.gz"
[[libstdcxx-extract_log]]
arch = "aarch64"
git-tree-sha1 = "479f78e4ce398e560abb0de1baa2ae63548b03a1"
lazy = true
libc = "glibc"
os = "linux"

    [[libstdcxx-extract_log.download]]
    sha256 = "77760e6fc661aa47fce9d805c1f123da228288f307e8449f78c476e55ed028a5"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/libstdcxx-extract_log-v14.2.0-aarch64-linux-gnu.tar.gz"
[[libstdcxx-extract_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "77b44587c946d6ab10f4e75c6f6f2423025e1c59"
lazy = true
libc = "glibc"
os = "linux"

    [[libstdcxx-extract_log.download]]
    sha256 = "784fe876226b769b58d11a12f8334e69a6ea2f1b956aac0be737959c418753bb"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/libstdcxx-extract_log-v14.2.0-armv6l-linux-gnueabihf.tar.gz"
[[libstdcxx-extract_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a972c52a11b3abb7cbc3c29e7c5681ef7fc3d42c"
lazy = true
libc = "glibc"
os = "linux"

    [[libstdcxx-extract_log.download]]
    sha256 = "cd70e969077d92580502af64de3028e9b25340227e0c4571ae7cdfec1f497109"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/libstdcxx-extract_log-v14.2.0-armv7l-linux-gnueabihf.tar.gz"
[[libstdcxx-extract_log]]
arch = "powerpc64le"
git-tree-sha1 = "fbfe53c635a45370997fbe395611091640068510"
lazy = true
libc = "glibc"
os = "linux"

    [[libstdcxx-extract_log.download]]
    sha256 = "91fdd0b525b06d0ef73324b1491e8580d0daf64f0d501eec836700381faffc36"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/libstdcxx-extract_log-v14.2.0-powerpc64le-linux-gnu.tar.gz"
[[libstdcxx-extract_log]]
arch = "x86_64"
git-tree-sha1 = "ac5b15e7df862dc0a78d5fa6c862946deb6a2518"
lazy = true
libc = "musl"
os = "linux"

    [[libstdcxx-extract_log.download]]
    sha256 = "797e7a30dccadcc8a6e2c74913464dad9372b87ab5637398e860cd466c7172c9"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/libstdcxx-extract_log-v14.2.0-x86_64-linux-musl.tar.gz"
[[libstdcxx-extract_log]]
arch = "i686"
git-tree-sha1 = "111e3f8d4b39ed0e212049779b54ff31b9ba3386"
lazy = true
libc = "musl"
os = "linux"

    [[libstdcxx-extract_log.download]]
    sha256 = "b1314be843a8217f53a8a7faf42d912a3724a88eeb67b0c15fd856c3e1f3a402"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/libstdcxx-extract_log-v14.2.0-i686-linux-musl.tar.gz"
[[libstdcxx-extract_log]]
arch = "aarch64"
git-tree-sha1 = "811ffb6ac4f4d63419bd6f913cd4197ffa370825"
lazy = true
libc = "musl"
os = "linux"

    [[libstdcxx-extract_log.download]]
    sha256 = "03446f9f6fa88f0c5b377ca0b3f721e27dae974008a8bce273c153897f732340"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/libstdcxx-extract_log-v14.2.0-aarch64-linux-musl.tar.gz"
[[libstdcxx-extract_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "5d379ec45da07ec50f59372fa62a114f3affc34e"
lazy = true
libc = "musl"
os = "linux"

    [[libstdcxx-extract_log.download]]
    sha256 = "28e6d72b0f067278120854796f73257b2602f88b004f9468381bd4c5d8159fe0"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/libstdcxx-extract_log-v14.2.0-armv6l-linux-musleabihf.tar.gz"
[[libstdcxx-extract_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1c89fdf89b2143d2162b75c02c35304d8d2ee6f1"
lazy = true
libc = "musl"
os = "linux"

    [[libstdcxx-extract_log.download]]
    sha256 = "46a44679bcfe89b69893f257441bc53df6636e1d1d55d8b35a58a330517acdeb"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/libstdcxx-extract_log-v14.2.0-armv7l-linux-musleabihf.tar.gz"
[[libstdcxx-extract_log]]
arch = "x86_64"
git-tree-sha1 = "610cfd53529b967b9aaa406c6b3bbc32f334819b"
lazy = true
os = "windows"

    [[libstdcxx-extract_log.download]]
    sha256 = "63dc8fd7a9649ac21806b4b75cccdcb46ea4f806bb2e02e353b48e2d31d40b42"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/libstdcxx-extract_log-v14.2.0-x86_64-w64-mingw32.tar.gz"
[[libstdcxx-extract_log]]
arch = "i686"
git-tree-sha1 = "b9a38d37751f150be98c21ac5d96b94bd83bcb4d"
lazy = true
os = "windows"

    [[libstdcxx-extract_log.download]]
    sha256 = "380bcf59ec085b73b851ad8b27d8e35750b2f15b3b6f5245581045a050026836"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/libstdcxx-extract_log-v14.2.0-i686-w64-mingw32.tar.gz"
[[libstdcxx-extract_log]]
arch = "x86_64"
git-tree-sha1 = "6ee5cad4991967fa5e26ce26603fba8befe9c668"
lazy = true
os = "macos"

    [[libstdcxx-extract_log.download]]
    sha256 = "22f98f3c2a08b5e9f9d391b06a2483f9d922ec413bdd4cd39c58a1ec487b1c3b"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/libstdcxx-extract_log-v14.2.0-x86_64-apple-darwin.tar.gz"
[[libstdcxx-extract_log]]
arch = "aarch64"
git-tree-sha1 = "d6c6fb50e3c170c1eab386c74d19dbc728e7cf51"
lazy = true
os = "macos"

    [[libstdcxx-extract_log.download]]
    sha256 = "09a4ca032f4238b703455ed0a5281ff624ba2a231dc76af2f11b92c9482a02fa"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/libstdcxx-extract_log-v14.2.0-aarch64-apple-darwin.tar.gz"
