[[libstdcxx]]
arch = "x86_64"
git-tree-sha1 = "91e21ed43e85ed5d60ac921a4243e3056d1a54d9"
os = "macos"

    [[libstdcxx.download]]
    sha256 = "e84108d5ba27aaf88cb1612afb47409cc0285d33670582bc419add522a633e28"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0/libstdcxx-v14.2.0-x86_64-apple-darwin.tar.gz"

[[libstdcxx-build_log]]
arch = "x86_64"
git-tree-sha1 = "675200a94ce1a0b7559ba616daaf45b7156cd801"
lazy = true
os = "macos"

    [[libstdcxx-build_log.download]]
    sha256 = "f00682c624181b210da7215be5039f66d0df866eb52f6bae654dde4af54c6acd"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0/libstdcxx-build_log-v14.2.0-x86_64-apple-darwin.tar.gz"

[[libstdcxx-extract_log]]
arch = "x86_64"
git-tree-sha1 = "f567dc78da74e786ef9602fe70e7fb282c19e8ac"
lazy = true
os = "macos"

    [[libstdcxx-extract_log.download]]
    sha256 = "1d871adb5ed46f09bc80ed008ee66fd0c5dd107bb444ed9d101647b53416105a"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0/libstdcxx-extract_log-v14.2.0-x86_64-apple-darwin.tar.gz"
