[[libstdcxx]]
arch = "aarch64"
git-tree-sha1 = "73fb408b7ba897be6a75b75127537ec87a2363d8"
os = "macos"

    [[libstdcxx.download]]
    sha256 = "d13a5130fa89dcda3c12a7d2f78c40dc8348c74f4adee05fb0ffeaba7d3a6443"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0/libstdcxx-v14.2.0-aarch64-apple-darwin.tar.gz"
[[libstdcxx]]
arch = "x86_64"
git-tree-sha1 = "822b20ef19d1f9b72178a805e5ab18758201d6d7"
os = "macos"

    [[libstdcxx.download]]
    sha256 = "658a303140df76f720c698e7294cdfe3917b1c9720dfc33964ce63fbe0b6c794"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0/libstdcxx-v14.2.0-x86_64-apple-darwin.tar.gz"

[[libstdcxx-build_log]]
arch = "aarch64"
git-tree-sha1 = "08184663c064d7c03ed2a894bb52692e81a0bb52"
lazy = true
os = "macos"

    [[libstdcxx-build_log.download]]
    sha256 = "adf5543dbf16f8c1b8e7fc913c10ed87b7189a3c2b41913b3b45e04a4cf22cf8"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0/libstdcxx-build_log-v14.2.0-aarch64-apple-darwin.tar.gz"
[[libstdcxx-build_log]]
arch = "x86_64"
git-tree-sha1 = "7533848b2086adc3cbdcd5de9bf4a76da55f7337"
lazy = true
os = "macos"

    [[libstdcxx-build_log.download]]
    sha256 = "3d527feac3f4fbca8bf1b7831049a0c17971c654f2cbe70082e33cf3db99c94b"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0/libstdcxx-build_log-v14.2.0-x86_64-apple-darwin.tar.gz"

[[libstdcxx-extract_log]]
arch = "aarch64"
git-tree-sha1 = "fe2ff73cf4e246d7b455c01f84ef8c825081e35b"
lazy = true
os = "macos"

    [[libstdcxx-extract_log.download]]
    sha256 = "5d0dfec4a98927c2c4b172cfcd25bb8033a8a9db37038b6d3342cd212428196f"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0/libstdcxx-extract_log-v14.2.0-aarch64-apple-darwin.tar.gz"
[[libstdcxx-extract_log]]
arch = "x86_64"
git-tree-sha1 = "dad70bd45d1dd792c021727d750de93b1af79dda"
lazy = true
os = "macos"

    [[libstdcxx-extract_log.download]]
    sha256 = "46bfee3a0ff090117e3491458f177d56efd0c6912e28fdf3cf4f61f675d72846"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0/libstdcxx-extract_log-v14.2.0-x86_64-apple-darwin.tar.gz"
