[[libstdcxx]]
arch = "x86_64"
git-tree-sha1 = "68f0032234b52253dfdd7bdaedc5be2b56fdaf4b"
libc = "glibc"
os = "linux"

    [[libstdcxx.download]]
    sha256 = "95d51c9c1dc589323bf011f6e8ce234863739e503847634d73d842d0666d6b3b"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0/libstdcxx-v14.2.0-x86_64-linux-gnu.tar.gz"
[[libstdcxx]]
arch = "i686"
git-tree-sha1 = "eed08fe53cccec105ad75fbed6c30fa3eaf4a6d3"
libc = "glibc"
os = "linux"

    [[libstdcxx.download]]
    sha256 = "416fd5617d07a442cc474edf0e86ef5345da9c581a9223e799ead63b94577105"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0/libstdcxx-v14.2.0-i686-linux-gnu.tar.gz"
[[libstdcxx]]
arch = "aarch64"
git-tree-sha1 = "83ab048965a8152ac698123c96861bc22d94d7de"
libc = "glibc"
os = "linux"

    [[libstdcxx.download]]
    sha256 = "1c50542f4734e169ce6eedc6752798ca7ee00ab574647d13880f7797726e9fe6"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0/libstdcxx-v14.2.0-aarch64-linux-gnu.tar.gz"
[[libstdcxx]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "123f5c9cb2f6561f179d9c8fad656ce27a5e36b7"
libc = "glibc"
os = "linux"

    [[libstdcxx.download]]
    sha256 = "4a644a6f75443619d7897a72fd91fd94bec7d9d666e92cec43935b61b9f19496"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0/libstdcxx-v14.2.0-armv6l-linux-gnueabihf.tar.gz"
[[libstdcxx]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6f265296cf7c200a05241bf900d9a3e506fa3883"
libc = "glibc"
os = "linux"

    [[libstdcxx.download]]
    sha256 = "befc0c2f6bcc805792d8b24abdf9704956a896f8c42a896075ea53e46a0533a4"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0/libstdcxx-v14.2.0-armv7l-linux-gnueabihf.tar.gz"
[[libstdcxx]]
arch = "powerpc64le"
git-tree-sha1 = "2e123a7fb6bb5622f375df67d665d422c43e48dc"
libc = "glibc"
os = "linux"

    [[libstdcxx.download]]
    sha256 = "8ac2e42d12ee3190aa3844035232e89088874b84c34230ccd18400f71345e027"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0/libstdcxx-v14.2.0-powerpc64le-linux-gnu.tar.gz"
[[libstdcxx]]
arch = "x86_64"
git-tree-sha1 = "e76e9419624179d31ea57f0a552ffd8e9026c3ec"
libc = "musl"
os = "linux"

    [[libstdcxx.download]]
    sha256 = "ac390aa2246db78f0c83ef15e2521e02cbe9b560fd4f8817dafb00551d264fab"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0/libstdcxx-v14.2.0-x86_64-linux-musl.tar.gz"
[[libstdcxx]]
arch = "i686"
git-tree-sha1 = "fdf5e4b3d5e9e9edf2fc963284282d37e4d92f86"
libc = "musl"
os = "linux"

    [[libstdcxx.download]]
    sha256 = "a1f66a7d2f0d494626ee85ecc6de55c0a8418e6945ead7324156e0fa6fcc0141"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0/libstdcxx-v14.2.0-i686-linux-musl.tar.gz"
[[libstdcxx]]
arch = "aarch64"
git-tree-sha1 = "bafc9a8c4bf92376df4b644e0b169a4fc91122ec"
libc = "musl"
os = "linux"

    [[libstdcxx.download]]
    sha256 = "bb1c96ea6ac04cc06ff1c32782b93b3a84226072145acc4067cb31294d184d17"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0/libstdcxx-v14.2.0-aarch64-linux-musl.tar.gz"
[[libstdcxx]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "196da2ca2c4fab2796a361e91a7916c012704106"
libc = "musl"
os = "linux"

    [[libstdcxx.download]]
    sha256 = "cc527d79c7b0da5bb9beff712fdb13aefd2d2b2ece7b084cc42a97724be880e4"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0/libstdcxx-v14.2.0-armv6l-linux-musleabihf.tar.gz"
[[libstdcxx]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7dc318533f4209d64fe16cfb023f787f6418077d"
libc = "musl"
os = "linux"

    [[libstdcxx.download]]
    sha256 = "238e0bb69cf3632263559bf9cfa9ea1f108e589ae372acbaba006d6fd2c45177"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0/libstdcxx-v14.2.0-armv7l-linux-musleabihf.tar.gz"
[[libstdcxx]]
arch = "x86_64"
git-tree-sha1 = "03e1cfbdba0c77a759cc90cd9e1af05a4ac7c787"
os = "windows"

    [[libstdcxx.download]]
    sha256 = "7d571f895a47fc1a02a647ecce2f4d4f73e5f5717ef247c38c36ace0a3298ccf"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0/libstdcxx-v14.2.0-x86_64-w64-mingw32.tar.gz"
[[libstdcxx]]
arch = "i686"
git-tree-sha1 = "bcb6425afea9c62f61537a44eda431edd8f221bd"
os = "windows"

    [[libstdcxx.download]]
    sha256 = "398e58e449d3e394ecbb86896492a7893193f5b33f438ba381d1df6aa7ce552b"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0/libstdcxx-v14.2.0-i686-w64-mingw32.tar.gz"
[[libstdcxx]]
arch = "x86_64"
git-tree-sha1 = "0e4265b00af1be98a7ccc2847a9f293f4fb53e03"
os = "macos"

    [[libstdcxx.download]]
    sha256 = "dae571c3c93bc46e9f243df71db5bc535d675d7f775c9174159eb3e4d24a9722"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0/libstdcxx-v14.2.0-x86_64-apple-darwin.tar.gz"
[[libstdcxx]]
arch = "aarch64"
git-tree-sha1 = "c6447c5a42aceb0ba42419991051211a3db0d51d"
os = "macos"

    [[libstdcxx.download]]
    sha256 = "113a78c736782b71db634abc09bdc25810788949671aa571d2ac513143b26e59"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0/libstdcxx-v14.2.0-aarch64-apple-darwin.tar.gz"

[[libstdcxx-build_log]]
arch = "x86_64"
git-tree-sha1 = "123b1469f104d47d9835925c9212ed382a682fdc"
lazy = true
libc = "glibc"
os = "linux"

    [[libstdcxx-build_log.download]]
    sha256 = "c097937e95318c615eea8976b17ba08deb07b0a4fc3580bd4019fa3fb2fc2310"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0/libstdcxx-build_log-v14.2.0-x86_64-linux-gnu.tar.gz"
[[libstdcxx-build_log]]
arch = "i686"
git-tree-sha1 = "1967cdf47d9dac8237735fdbf6978669afa3c74d"
lazy = true
libc = "glibc"
os = "linux"

    [[libstdcxx-build_log.download]]
    sha256 = "ab5092967670f24199a2715f15a6995ae8d963c092c7e74344fe8998353d96b8"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0/libstdcxx-build_log-v14.2.0-i686-linux-gnu.tar.gz"
[[libstdcxx-build_log]]
arch = "aarch64"
git-tree-sha1 = "6f349c942500f1323f62d58a129de8b3557a4f93"
lazy = true
libc = "glibc"
os = "linux"

    [[libstdcxx-build_log.download]]
    sha256 = "bd61e1b8d98570aea180c4c6a6e499ebc1158d97b489823e3e4ac3670c442315"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0/libstdcxx-build_log-v14.2.0-aarch64-linux-gnu.tar.gz"
[[libstdcxx-build_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "2e06e2c2b7b72e67dd5ae7f31663561e1823ec64"
lazy = true
libc = "glibc"
os = "linux"

    [[libstdcxx-build_log.download]]
    sha256 = "dace30f24c0cb5ddb7826b9a3f4867c3b0683e6423f88b43b58b6d2ee785c8ad"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0/libstdcxx-build_log-v14.2.0-armv6l-linux-gnueabihf.tar.gz"
[[libstdcxx-build_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "18d49b663474679964ea4161c5ee6250353f4327"
lazy = true
libc = "glibc"
os = "linux"

    [[libstdcxx-build_log.download]]
    sha256 = "92aae3a7e25d9628f90c2638c166673d830a055f13f90d709feda6908ec89140"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0/libstdcxx-build_log-v14.2.0-armv7l-linux-gnueabihf.tar.gz"
[[libstdcxx-build_log]]
arch = "powerpc64le"
git-tree-sha1 = "82dc462e262db402193e461fd252c4aa285175fe"
lazy = true
libc = "glibc"
os = "linux"

    [[libstdcxx-build_log.download]]
    sha256 = "d0b8d6d00e7cb454de355b10bbc098f279e0f04f3308c4a99ee6d979cc8af15c"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0/libstdcxx-build_log-v14.2.0-powerpc64le-linux-gnu.tar.gz"
[[libstdcxx-build_log]]
arch = "x86_64"
git-tree-sha1 = "ab907ee1cc8a1f3fb4ebdf36727802abee081d37"
lazy = true
libc = "musl"
os = "linux"

    [[libstdcxx-build_log.download]]
    sha256 = "94e3418bcc1c06f7d45b28fea6fb256576cd7e6c53cf3d0bd4141c44a732b48c"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0/libstdcxx-build_log-v14.2.0-x86_64-linux-musl.tar.gz"
[[libstdcxx-build_log]]
arch = "i686"
git-tree-sha1 = "5a893a577c6400c83b0eb5fb304a53aecc0bb2d3"
lazy = true
libc = "musl"
os = "linux"

    [[libstdcxx-build_log.download]]
    sha256 = "59192a59caf68990dc32e6e9be588521b2c93d0669ff919271a85e3a8db26bfc"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0/libstdcxx-build_log-v14.2.0-i686-linux-musl.tar.gz"
[[libstdcxx-build_log]]
arch = "aarch64"
git-tree-sha1 = "65d77e77404b160d1ac8f02f7b08c820d2e10896"
lazy = true
libc = "musl"
os = "linux"

    [[libstdcxx-build_log.download]]
    sha256 = "2db064c2ddd971a9ad98672134165a9c99e2aa495fe52254b8e74e978cfbc390"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0/libstdcxx-build_log-v14.2.0-aarch64-linux-musl.tar.gz"
[[libstdcxx-build_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7b4f0c8a2d98d45e27b9b2e6cb4c7f7fea60bf04"
lazy = true
libc = "musl"
os = "linux"

    [[libstdcxx-build_log.download]]
    sha256 = "d1555c4bd73e7fc1332b3bb98f6b297ab7b7465b5af67a454d8439ff6ba3f7cf"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0/libstdcxx-build_log-v14.2.0-armv6l-linux-musleabihf.tar.gz"
[[libstdcxx-build_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "684c3ff5d3794230baea4debf77f53a3d9815bd7"
lazy = true
libc = "musl"
os = "linux"

    [[libstdcxx-build_log.download]]
    sha256 = "7d2b814532036faa7330093665e541eb217b679c8202761d37c4bf2cc008f4ff"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0/libstdcxx-build_log-v14.2.0-armv7l-linux-musleabihf.tar.gz"
[[libstdcxx-build_log]]
arch = "x86_64"
git-tree-sha1 = "b77e641837ba8d30b102a04db95ff64975fc17b7"
lazy = true
os = "windows"

    [[libstdcxx-build_log.download]]
    sha256 = "85b536bb9463534184f73485b1216ead3b6e335242f7c737b55f8f42bccda68e"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0/libstdcxx-build_log-v14.2.0-x86_64-w64-mingw32.tar.gz"
[[libstdcxx-build_log]]
arch = "i686"
git-tree-sha1 = "313c2370f73b9af7abf8b9162aade7725dd9919e"
lazy = true
os = "windows"

    [[libstdcxx-build_log.download]]
    sha256 = "deba85225e159e47952efc562cb778b0f5a58ebce8194d7022b68ae3e94efc08"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0/libstdcxx-build_log-v14.2.0-i686-w64-mingw32.tar.gz"
[[libstdcxx-build_log]]
arch = "x86_64"
git-tree-sha1 = "6915231346968d4501e98fb958f56ec0a3551ab6"
lazy = true
os = "macos"

    [[libstdcxx-build_log.download]]
    sha256 = "5c260ba37b1ac8532d195ae06aaa73833d3207854ec7bba3420c17345daaa6b9"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0/libstdcxx-build_log-v14.2.0-x86_64-apple-darwin.tar.gz"
[[libstdcxx-build_log]]
arch = "aarch64"
git-tree-sha1 = "6149df285c0836cb668d75a22c8340721dfdc05b"
lazy = true
os = "macos"

    [[libstdcxx-build_log.download]]
    sha256 = "6dc62905301e73512b94b3971c8b86c8d6be72942c11036733784ec902d74a0b"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0/libstdcxx-build_log-v14.2.0-aarch64-apple-darwin.tar.gz"

[[libstdcxx-extract_log]]
arch = "x86_64"
git-tree-sha1 = "e294f1e08d24b3a313da712696ffe875ea4f6ab6"
lazy = true
libc = "glibc"
os = "linux"

    [[libstdcxx-extract_log.download]]
    sha256 = "43e9732e5f24144afdb065b150adf5c62cdf1ee25258361a7de981f1577624f8"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0/libstdcxx-extract_log-v14.2.0-x86_64-linux-gnu.tar.gz"
[[libstdcxx-extract_log]]
arch = "i686"
git-tree-sha1 = "0d6b699be4ef99a0dac7d4eb0aa68c13670c2963"
lazy = true
libc = "glibc"
os = "linux"

    [[libstdcxx-extract_log.download]]
    sha256 = "cde28b974648aad33c3833e5d1cf6d93f626a648ab2bccf86b52dc4a13bf87cd"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0/libstdcxx-extract_log-v14.2.0-i686-linux-gnu.tar.gz"
[[libstdcxx-extract_log]]
arch = "aarch64"
git-tree-sha1 = "e87a61acf109e66b8460aab7f22f4f9191d3bbca"
lazy = true
libc = "glibc"
os = "linux"

    [[libstdcxx-extract_log.download]]
    sha256 = "bbf6db5ebf17a8bc2b7887e654d3c586eee0bc709f93f056f041b86b27774c21"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0/libstdcxx-extract_log-v14.2.0-aarch64-linux-gnu.tar.gz"
[[libstdcxx-extract_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "89b1b8b9bbdf97c7b6f95fe3fb59083019e67e58"
lazy = true
libc = "glibc"
os = "linux"

    [[libstdcxx-extract_log.download]]
    sha256 = "ac2e03f75234051e798d717cec08e3d7e59090322ee1ec4f3acf554f679461cd"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0/libstdcxx-extract_log-v14.2.0-armv6l-linux-gnueabihf.tar.gz"
[[libstdcxx-extract_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "37e9d52a8b774f7562df25f1d41b2e4985699874"
lazy = true
libc = "glibc"
os = "linux"

    [[libstdcxx-extract_log.download]]
    sha256 = "50ddcc950a11545725fb3063253091178145a282630282a9c3df421ede38363f"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0/libstdcxx-extract_log-v14.2.0-armv7l-linux-gnueabihf.tar.gz"
[[libstdcxx-extract_log]]
arch = "powerpc64le"
git-tree-sha1 = "6faf842e95572c2bf7e5d53a8d7579aa5538adbe"
lazy = true
libc = "glibc"
os = "linux"

    [[libstdcxx-extract_log.download]]
    sha256 = "b540f39a9d9a8eba1355f5174bd5560328544ea03a6a9f8be5cac6bd7178add2"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0/libstdcxx-extract_log-v14.2.0-powerpc64le-linux-gnu.tar.gz"
[[libstdcxx-extract_log]]
arch = "x86_64"
git-tree-sha1 = "e36c07d19bea446f782602998c78947f5b7bd4e2"
lazy = true
libc = "musl"
os = "linux"

    [[libstdcxx-extract_log.download]]
    sha256 = "2f7bbba3bde796c8c2b3c79d7a014a73a769996fd0709cb67d9b445d68df1ee0"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0/libstdcxx-extract_log-v14.2.0-x86_64-linux-musl.tar.gz"
[[libstdcxx-extract_log]]
arch = "i686"
git-tree-sha1 = "85df432f25e25aa3f2b628bdd4cfaf6a7c960b66"
lazy = true
libc = "musl"
os = "linux"

    [[libstdcxx-extract_log.download]]
    sha256 = "5512667160f68122cfaa73b3fa222517c44b713c13b1eef27a271f1174074831"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0/libstdcxx-extract_log-v14.2.0-i686-linux-musl.tar.gz"
[[libstdcxx-extract_log]]
arch = "aarch64"
git-tree-sha1 = "13246a4033183a40da50770f5350cb9a3ac3def9"
lazy = true
libc = "musl"
os = "linux"

    [[libstdcxx-extract_log.download]]
    sha256 = "2d6daf1ed0e17ecc0ba7a1f5b63c48a13183e286c3668b812a8c4ebc1c90a6fe"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0/libstdcxx-extract_log-v14.2.0-aarch64-linux-musl.tar.gz"
[[libstdcxx-extract_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "6d92d9183e19a671fa50047e6a8512f43502f667"
lazy = true
libc = "musl"
os = "linux"

    [[libstdcxx-extract_log.download]]
    sha256 = "45a5ee0627b63dfa31ef1df48e8200eadf1d280d8223d8a686326b614f0a715e"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0/libstdcxx-extract_log-v14.2.0-armv6l-linux-musleabihf.tar.gz"
[[libstdcxx-extract_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0657dadf7f96615b2aeb6a54d1219ccce4679f5a"
lazy = true
libc = "musl"
os = "linux"

    [[libstdcxx-extract_log.download]]
    sha256 = "4e9246585c5762c38f4e5998b6c30fa33e6378815d89a3ae9c19cfab20e67b4b"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0/libstdcxx-extract_log-v14.2.0-armv7l-linux-musleabihf.tar.gz"
[[libstdcxx-extract_log]]
arch = "x86_64"
git-tree-sha1 = "2cc540478000ebc67a992dc8bb076f669111828e"
lazy = true
os = "windows"

    [[libstdcxx-extract_log.download]]
    sha256 = "808330cb40dcc32a2c11aea89145e1b3a5050d6633220131a9a2b9d80154e321"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0/libstdcxx-extract_log-v14.2.0-x86_64-w64-mingw32.tar.gz"
[[libstdcxx-extract_log]]
arch = "i686"
git-tree-sha1 = "63d06189bc8723a07f91eb19d7bd7e35a68d076b"
lazy = true
os = "windows"

    [[libstdcxx-extract_log.download]]
    sha256 = "7189163c3bef0c2091760cacd71aeeff200b6af34018ed8edfea3ca453ffd0c5"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0/libstdcxx-extract_log-v14.2.0-i686-w64-mingw32.tar.gz"
[[libstdcxx-extract_log]]
arch = "x86_64"
git-tree-sha1 = "d0432070a29bb54aeedfb733f5f18298eecaad3d"
lazy = true
os = "macos"

    [[libstdcxx-extract_log.download]]
    sha256 = "64f34a15babb7ab39ac65575fa4139e1f5901feae0738d309f64158a210be7b0"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0/libstdcxx-extract_log-v14.2.0-x86_64-apple-darwin.tar.gz"
[[libstdcxx-extract_log]]
arch = "aarch64"
git-tree-sha1 = "83ac46f720ae43a61a5db40a478ecbf420d72b31"
lazy = true
os = "macos"

    [[libstdcxx-extract_log.download]]
    sha256 = "6c45cb146544e87a56cf4f8ef6a9ef5ef89dfc8715047c6c5f3c9230f267283e"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0/libstdcxx-extract_log-v14.2.0-aarch64-apple-darwin.tar.gz"
