[[libstdcxx]]
arch = "x86_64"
git-tree-sha1 = "9458d0a9b355ede6670795fdfa9274a1e7b06983"
libc = "glibc"
os = "linux"

    [[libstdcxx.download]]
    sha256 = "ce7fe471a382e056321991b4da3b7dd65e904f1ef821f74cdbd45987505275ca"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v9.1.0-GCC/libstdcxx-v9.1.0-x86_64-linux-gnu.tar.gz"
[[libstdcxx]]
arch = "i686"
git-tree-sha1 = "8e47165ce4030c95cc01967e96e804e413bf0be9"
libc = "glibc"
os = "linux"

    [[libstdcxx.download]]
    sha256 = "aa60d9b94d76df992d82000e3a4ed7869d85818896dcc723bfdf3b6eefe8f96f"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v9.1.0-GCC/libstdcxx-v9.1.0-i686-linux-gnu.tar.gz"
[[libstdcxx]]
arch = "aarch64"
git-tree-sha1 = "dac1ba91f1ba7a06867f6719de2d46ec7b285179"
libc = "glibc"
os = "linux"

    [[libstdcxx.download]]
    sha256 = "70e2140d1f6088f55b7924fe383cf50479c540104c39935ca09acf993fd563ef"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v9.1.0-GCC/libstdcxx-v9.1.0-aarch64-linux-gnu.tar.gz"
[[libstdcxx]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "c1a72833c495e32a60d9740c4d8135fc2724ff82"
libc = "glibc"
os = "linux"

    [[libstdcxx.download]]
    sha256 = "47f5dbab5824cc5fb1f7cd6c82d8af96e304f127b9f5c99eec8606dd5744bb06"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v9.1.0-GCC/libstdcxx-v9.1.0-armv6l-linux-gnueabihf.tar.gz"
[[libstdcxx]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b54de303f558582a749f97de56557fa092a04ffd"
libc = "glibc"
os = "linux"

    [[libstdcxx.download]]
    sha256 = "99428c3c56f2747c9f66da43ef3b9848add022a8fdba06d5c5e7fe441c07409a"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v9.1.0-GCC/libstdcxx-v9.1.0-armv7l-linux-gnueabihf.tar.gz"
[[libstdcxx]]
arch = "powerpc64le"
git-tree-sha1 = "a3b2505ad2a6cb3e37a8d4318d4679ff5f01ddd4"
libc = "glibc"
os = "linux"

    [[libstdcxx.download]]
    sha256 = "e148b93cf5e5fe0032e9155dc5fcee54a7edc1d0e539eaa70a771f34a1f64b46"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v9.1.0-GCC/libstdcxx-v9.1.0-powerpc64le-linux-gnu.tar.gz"
[[libstdcxx]]
arch = "x86_64"
git-tree-sha1 = "8f04804f9118d5fbdeb217cda4f26a110c0de251"
libc = "musl"
os = "linux"

    [[libstdcxx.download]]
    sha256 = "4b019c7999024f9d4f71c992dc0591aacf5a5032d814669a31b7801da8a06926"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v9.1.0-GCC/libstdcxx-v9.1.0-x86_64-linux-musl.tar.gz"
[[libstdcxx]]
arch = "i686"
git-tree-sha1 = "4fb71fdfde1655a454841174b26b6c4042ff817e"
libc = "musl"
os = "linux"

    [[libstdcxx.download]]
    sha256 = "19fd641a40bf7006338dabc30ba4075c85a70a415157252ca4735e452c91bb00"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v9.1.0-GCC/libstdcxx-v9.1.0-i686-linux-musl.tar.gz"
[[libstdcxx]]
arch = "aarch64"
git-tree-sha1 = "70cd26a2a074e31a2495e8a9b65aad122ab79415"
libc = "musl"
os = "linux"

    [[libstdcxx.download]]
    sha256 = "09f684e84dae142ac3f4f1f7067f4cf4c808d495625e9234a94c0936e72e580f"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v9.1.0-GCC/libstdcxx-v9.1.0-aarch64-linux-musl.tar.gz"
[[libstdcxx]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "8bb33dd7fd2587fb83afc5ae45aecff6dde83f24"
libc = "musl"
os = "linux"

    [[libstdcxx.download]]
    sha256 = "de506be794d77ac56188e5da97d31e9081e74cd350db603526f97e925a9cd52f"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v9.1.0-GCC/libstdcxx-v9.1.0-armv6l-linux-musleabihf.tar.gz"
[[libstdcxx]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f296170038193250a814e4a4055b1d4ee9a2c569"
libc = "musl"
os = "linux"

    [[libstdcxx.download]]
    sha256 = "3f5122c0e893526f729f78d0259165270cc9eb71145681507609f19442d2f2a4"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v9.1.0-GCC/libstdcxx-v9.1.0-armv7l-linux-musleabihf.tar.gz"
[[libstdcxx]]
arch = "x86_64"
git-tree-sha1 = "6210a318218d85df632ceaa9ee1a9c233d04860e"
os = "windows"

    [[libstdcxx.download]]
    sha256 = "fefdbfd95f333992b41cb6e0d45d05d3de249eb786f5835a59c5c0db77f706f4"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v9.1.0-GCC/libstdcxx-v9.1.0-x86_64-w64-mingw32.tar.gz"
[[libstdcxx]]
arch = "i686"
git-tree-sha1 = "26ed1f7ebb29e7a60fd3f53dc9b9d42d9fb5bb81"
os = "windows"

    [[libstdcxx.download]]
    sha256 = "b3c691265f06ce24407e9aa5cc801cde108b4537ba72ae9254a16d56430d01db"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v9.1.0-GCC/libstdcxx-v9.1.0-i686-w64-mingw32.tar.gz"

[[libstdcxx-build_log]]
arch = "x86_64"
git-tree-sha1 = "452fcd4873742a111eca232eb513cc0454cc2771"
lazy = true
libc = "glibc"
os = "linux"

    [[libstdcxx-build_log.download]]
    sha256 = "87851af0b3dfe260ff3d5d98215dc724c9d05abc7917de7eab349836d1f79567"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v9.1.0-GCC/libstdcxx-build_log-v9.1.0-x86_64-linux-gnu.tar.gz"
[[libstdcxx-build_log]]
arch = "i686"
git-tree-sha1 = "4a250fe30b4e46797ed1cb56ac41b8120ddaa8a4"
lazy = true
libc = "glibc"
os = "linux"

    [[libstdcxx-build_log.download]]
    sha256 = "bf3ef16ead47bfa421b4370ca21222dcd1194322158f9206cccfb0d818a9b00f"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v9.1.0-GCC/libstdcxx-build_log-v9.1.0-i686-linux-gnu.tar.gz"
[[libstdcxx-build_log]]
arch = "aarch64"
git-tree-sha1 = "4d0668254cbe04bc3a7ff585580cad611a8d5a7b"
lazy = true
libc = "glibc"
os = "linux"

    [[libstdcxx-build_log.download]]
    sha256 = "3088e5883cbef4932800e3849eaca159827d1d77fd90e1081db94be6da56db78"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v9.1.0-GCC/libstdcxx-build_log-v9.1.0-aarch64-linux-gnu.tar.gz"
[[libstdcxx-build_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "6539ec0deae8052f09e03c9f3490f40c9b004760"
lazy = true
libc = "glibc"
os = "linux"

    [[libstdcxx-build_log.download]]
    sha256 = "6e94f87e61a641aaeafbf7265a7d59bcf2a037b5aedafab593e1267f4d83b66a"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v9.1.0-GCC/libstdcxx-build_log-v9.1.0-armv6l-linux-gnueabihf.tar.gz"
[[libstdcxx-build_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "48ab02beaf265a5a0746d388ce0ed8c3838b3b61"
lazy = true
libc = "glibc"
os = "linux"

    [[libstdcxx-build_log.download]]
    sha256 = "e2bff433ca6a4213353a3e8da6641e2c952edcaa8e2f9d9eecacdef34e4b4f9c"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v9.1.0-GCC/libstdcxx-build_log-v9.1.0-armv7l-linux-gnueabihf.tar.gz"
[[libstdcxx-build_log]]
arch = "powerpc64le"
git-tree-sha1 = "50cafaf60a5ef88da94ee581aada993f606bf436"
lazy = true
libc = "glibc"
os = "linux"

    [[libstdcxx-build_log.download]]
    sha256 = "ae40c8ab27a9d9be2f30c514b8fcb49ec6434a3e14a744f476769d13312192ff"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v9.1.0-GCC/libstdcxx-build_log-v9.1.0-powerpc64le-linux-gnu.tar.gz"
[[libstdcxx-build_log]]
arch = "x86_64"
git-tree-sha1 = "7fc91a4bfc1cf90bd7f457cff5ab7c84ce168b0a"
lazy = true
libc = "musl"
os = "linux"

    [[libstdcxx-build_log.download]]
    sha256 = "8b54596c170a3b14223b5ba35ace338c1c2c5d947cf0228863e301afc1bbb493"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v9.1.0-GCC/libstdcxx-build_log-v9.1.0-x86_64-linux-musl.tar.gz"
[[libstdcxx-build_log]]
arch = "i686"
git-tree-sha1 = "a3f8ab305f7f3750bd67accf9bd1868bac1f42ac"
lazy = true
libc = "musl"
os = "linux"

    [[libstdcxx-build_log.download]]
    sha256 = "87e347b233016ad805ac1f7424f63eb6443e628dd1406f9d38018252ecc95d50"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v9.1.0-GCC/libstdcxx-build_log-v9.1.0-i686-linux-musl.tar.gz"
[[libstdcxx-build_log]]
arch = "aarch64"
git-tree-sha1 = "c19926d76852285d6723df7c15f3e8c7288ae428"
lazy = true
libc = "musl"
os = "linux"

    [[libstdcxx-build_log.download]]
    sha256 = "2c9a66a0d9b7f6e2a71f80412f7aca06474785a500b474393c5fbbf5a40a6d0e"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v9.1.0-GCC/libstdcxx-build_log-v9.1.0-aarch64-linux-musl.tar.gz"
[[libstdcxx-build_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "56a1300de92cb559088b61133e6ede4e7c6da210"
lazy = true
libc = "musl"
os = "linux"

    [[libstdcxx-build_log.download]]
    sha256 = "60363dce03534239f2b4abc00b8c7030056d5f7bda700c262d83fabe34e1936b"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v9.1.0-GCC/libstdcxx-build_log-v9.1.0-armv6l-linux-musleabihf.tar.gz"
[[libstdcxx-build_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "3aca58e29d02139ada4502664d021cb48618767a"
lazy = true
libc = "musl"
os = "linux"

    [[libstdcxx-build_log.download]]
    sha256 = "fa5667345678d1feb91683f1726dd7e6d24a1e9dae1dae7464f4c001b32ffb19"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v9.1.0-GCC/libstdcxx-build_log-v9.1.0-armv7l-linux-musleabihf.tar.gz"
[[libstdcxx-build_log]]
arch = "x86_64"
git-tree-sha1 = "e85245541c57aca4b85c3848f6e7d07b7d87d556"
lazy = true
os = "windows"

    [[libstdcxx-build_log.download]]
    sha256 = "418783c982ddfa23a08287b2fc914688e1d77ad276b04a8c8937fc9aacf1027f"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v9.1.0-GCC/libstdcxx-build_log-v9.1.0-x86_64-w64-mingw32.tar.gz"
[[libstdcxx-build_log]]
arch = "i686"
git-tree-sha1 = "ff6896d1656156031fd157e7e2df0464d613e876"
lazy = true
os = "windows"

    [[libstdcxx-build_log.download]]
    sha256 = "d223a0e10d53de663de935a8312fbc04407b58cb250504507e47a1f0ea462826"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v9.1.0-GCC/libstdcxx-build_log-v9.1.0-i686-w64-mingw32.tar.gz"

[[libstdcxx-extract_log]]
arch = "x86_64"
git-tree-sha1 = "3457f35c4e2a9a030e256400aead11c9c1b3df49"
lazy = true
libc = "glibc"
os = "linux"

    [[libstdcxx-extract_log.download]]
    sha256 = "b763fb3b63e91b06c27ec78b594b0480520fdf8548b4d96d6a8b9aa90b16e04b"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v9.1.0-GCC/libstdcxx-extract_log-v9.1.0-x86_64-linux-gnu.tar.gz"
[[libstdcxx-extract_log]]
arch = "i686"
git-tree-sha1 = "9320136cd785848868e1bfdf61488d23f2779051"
lazy = true
libc = "glibc"
os = "linux"

    [[libstdcxx-extract_log.download]]
    sha256 = "b06f611d74f83cb1e43daa5a12d26f9ead393a92b1aa1f0fb2a7e7f095c8c791"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v9.1.0-GCC/libstdcxx-extract_log-v9.1.0-i686-linux-gnu.tar.gz"
[[libstdcxx-extract_log]]
arch = "aarch64"
git-tree-sha1 = "a431e614f118591d4b01aec6d777049a03a8f877"
lazy = true
libc = "glibc"
os = "linux"

    [[libstdcxx-extract_log.download]]
    sha256 = "2aa29655dbe9bbc10b5bcdc94c53580d660d0aacff2d8e857d9b4dd257363ffb"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v9.1.0-GCC/libstdcxx-extract_log-v9.1.0-aarch64-linux-gnu.tar.gz"
[[libstdcxx-extract_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "cb20a66b88e5471415b4abb51a0877ac935bfb6b"
lazy = true
libc = "glibc"
os = "linux"

    [[libstdcxx-extract_log.download]]
    sha256 = "3cbe21e47448b59af943941fd5701367002431ab8c738e8cac4e6ba1ba1dd4a3"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v9.1.0-GCC/libstdcxx-extract_log-v9.1.0-armv6l-linux-gnueabihf.tar.gz"
[[libstdcxx-extract_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "89b14a74d62fa6607efcaf109bf5211d9ef8af06"
lazy = true
libc = "glibc"
os = "linux"

    [[libstdcxx-extract_log.download]]
    sha256 = "340ca6463840037ba90f241350bc7c00b941503bdfc8d09bc885c1c90ebdcd98"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v9.1.0-GCC/libstdcxx-extract_log-v9.1.0-armv7l-linux-gnueabihf.tar.gz"
[[libstdcxx-extract_log]]
arch = "powerpc64le"
git-tree-sha1 = "20bc94690e3ae70ff2e2d7601bd1951c72e51c37"
lazy = true
libc = "glibc"
os = "linux"

    [[libstdcxx-extract_log.download]]
    sha256 = "c4e5eea309014b4d17fa17c738ba0896c74c1f3d1e511d335a3b0208f30e2e51"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v9.1.0-GCC/libstdcxx-extract_log-v9.1.0-powerpc64le-linux-gnu.tar.gz"
[[libstdcxx-extract_log]]
arch = "x86_64"
git-tree-sha1 = "943543a49cb16c5fe8e51d6cfca03e0a83372c87"
lazy = true
libc = "musl"
os = "linux"

    [[libstdcxx-extract_log.download]]
    sha256 = "c6ab79758168b3ec06d01c8cbe9db29ebe5e50be82ca5cec40ca79ee1860ecdc"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v9.1.0-GCC/libstdcxx-extract_log-v9.1.0-x86_64-linux-musl.tar.gz"
[[libstdcxx-extract_log]]
arch = "i686"
git-tree-sha1 = "ba1735d1a60088cff76c39d2eadf8c0b560c4ec3"
lazy = true
libc = "musl"
os = "linux"

    [[libstdcxx-extract_log.download]]
    sha256 = "316302ae5406e95f2cf3e751d4236308430720e7134255790fd6bf714abb3d7d"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v9.1.0-GCC/libstdcxx-extract_log-v9.1.0-i686-linux-musl.tar.gz"
[[libstdcxx-extract_log]]
arch = "aarch64"
git-tree-sha1 = "9c9bb070dd96d83023c1d1579dc70bb376cb08bf"
lazy = true
libc = "musl"
os = "linux"

    [[libstdcxx-extract_log.download]]
    sha256 = "1eb63ec5d6b7f722daf3bf629a8e5a763f7f23681fdfc9f6ca06e5f816f5d8c2"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v9.1.0-GCC/libstdcxx-extract_log-v9.1.0-aarch64-linux-musl.tar.gz"
[[libstdcxx-extract_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a348c5e2c1c073c5a53dce60265de04b9e6a5d09"
lazy = true
libc = "musl"
os = "linux"

    [[libstdcxx-extract_log.download]]
    sha256 = "25379a9aa43404071d5985fb16daf343e3c7c09ca198eba5aa54e5b596c33ced"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v9.1.0-GCC/libstdcxx-extract_log-v9.1.0-armv6l-linux-musleabihf.tar.gz"
[[libstdcxx-extract_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f55584f7ad3726bacd0c6fca8f0fa932ea0713c2"
lazy = true
libc = "musl"
os = "linux"

    [[libstdcxx-extract_log.download]]
    sha256 = "892d9ede5eb1cbda02f5d2d60efa57b18ef17ed2d7b25a33d5b9ef37e89dcab8"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v9.1.0-GCC/libstdcxx-extract_log-v9.1.0-armv7l-linux-musleabihf.tar.gz"
[[libstdcxx-extract_log]]
arch = "x86_64"
git-tree-sha1 = "98eff60a55ede1b3fde7550c8366bab459971af2"
lazy = true
os = "windows"

    [[libstdcxx-extract_log.download]]
    sha256 = "007f076d526ae873ae4cc13a003e00195af1fe3666f7bc762fb766a86147aa0e"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v9.1.0-GCC/libstdcxx-extract_log-v9.1.0-x86_64-w64-mingw32.tar.gz"
[[libstdcxx-extract_log]]
arch = "i686"
git-tree-sha1 = "9a7d0f0dde2ee2b47ca7f33d8416366c9ed78ea5"
lazy = true
os = "windows"

    [[libstdcxx-extract_log.download]]
    sha256 = "4dc728cac8ce2c276d6de74fe58ea5e451e6888f7383082256e57f77c543ab9b"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v9.1.0-GCC/libstdcxx-extract_log-v9.1.0-i686-w64-mingw32.tar.gz"
