[[libstdcxx]]
arch = "x86_64"
git-tree-sha1 = "68f0032234b52253dfdd7bdaedc5be2b56fdaf4b"
libc = "glibc"
os = "linux"

    [[libstdcxx.download]]
    sha256 = "3ce8e6bfb971b555d11a01fe2c4cbe2ff606740cf3b1fa3f1039c8d23c5e6179"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0/libstdcxx-v14.2.0-x86_64-linux-gnu.tar.gz"
[[libstdcxx]]
arch = "i686"
git-tree-sha1 = "eed08fe53cccec105ad75fbed6c30fa3eaf4a6d3"
libc = "glibc"
os = "linux"

    [[libstdcxx.download]]
    sha256 = "83ddb825dddd94da604127f65e9e7d57a445e8262230cebe045d83b19ce8bd49"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0/libstdcxx-v14.2.0-i686-linux-gnu.tar.gz"
[[libstdcxx]]
arch = "aarch64"
git-tree-sha1 = "83ab048965a8152ac698123c96861bc22d94d7de"
libc = "glibc"
os = "linux"

    [[libstdcxx.download]]
    sha256 = "e99d61b3fac7ad6ca1811621b192353d9306e36d1d2b3cf1d64e0bc729f0d1f3"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0/libstdcxx-v14.2.0-aarch64-linux-gnu.tar.gz"
[[libstdcxx]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "123f5c9cb2f6561f179d9c8fad656ce27a5e36b7"
libc = "glibc"
os = "linux"

    [[libstdcxx.download]]
    sha256 = "ac7a7721f8db65125904338b5f6482afb0710c49820c824a641d44609ba7fb4e"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0/libstdcxx-v14.2.0-armv6l-linux-gnueabihf.tar.gz"
[[libstdcxx]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6f265296cf7c200a05241bf900d9a3e506fa3883"
libc = "glibc"
os = "linux"

    [[libstdcxx.download]]
    sha256 = "9e0c6806ae46282c12f96597b723c098463fbb5a3355b261b85770a8c118297d"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0/libstdcxx-v14.2.0-armv7l-linux-gnueabihf.tar.gz"
[[libstdcxx]]
arch = "powerpc64le"
git-tree-sha1 = "2e123a7fb6bb5622f375df67d665d422c43e48dc"
libc = "glibc"
os = "linux"

    [[libstdcxx.download]]
    sha256 = "64ce5ae844cf350080a0b6ead5b1d1b34c514a0a2accc4d24b2e50da8cbe83cb"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0/libstdcxx-v14.2.0-powerpc64le-linux-gnu.tar.gz"
[[libstdcxx]]
arch = "x86_64"
git-tree-sha1 = "e76e9419624179d31ea57f0a552ffd8e9026c3ec"
libc = "musl"
os = "linux"

    [[libstdcxx.download]]
    sha256 = "0d2934fada09443833be9e5603e49b7c676d888c40b1fc0dc1d867169630f7a4"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0/libstdcxx-v14.2.0-x86_64-linux-musl.tar.gz"
[[libstdcxx]]
arch = "i686"
git-tree-sha1 = "fdf5e4b3d5e9e9edf2fc963284282d37e4d92f86"
libc = "musl"
os = "linux"

    [[libstdcxx.download]]
    sha256 = "4bce046fea443ca7297ee57af152c76b74eeb21ff398d994de8c9644e54b7ee4"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0/libstdcxx-v14.2.0-i686-linux-musl.tar.gz"
[[libstdcxx]]
arch = "aarch64"
git-tree-sha1 = "bafc9a8c4bf92376df4b644e0b169a4fc91122ec"
libc = "musl"
os = "linux"

    [[libstdcxx.download]]
    sha256 = "eaa28fd5a7ed1f72603fdddc73780fa9cce7abd82c7149826d3b2ad9e246368f"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0/libstdcxx-v14.2.0-aarch64-linux-musl.tar.gz"
[[libstdcxx]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "196da2ca2c4fab2796a361e91a7916c012704106"
libc = "musl"
os = "linux"

    [[libstdcxx.download]]
    sha256 = "f42878555ef6017bcbcbdb6590c02fc5095f0da6b526b8e2e831d094ba68e387"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0/libstdcxx-v14.2.0-armv6l-linux-musleabihf.tar.gz"
[[libstdcxx]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7dc318533f4209d64fe16cfb023f787f6418077d"
libc = "musl"
os = "linux"

    [[libstdcxx.download]]
    sha256 = "88d8c30cb43c6cb8b466158921bac2e1034b08e7ce5d483ecb08f85cc1fa7a89"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0/libstdcxx-v14.2.0-armv7l-linux-musleabihf.tar.gz"
[[libstdcxx]]
arch = "x86_64"
git-tree-sha1 = "ee97a63cef30f22ef77f00ccaabea0f81bc39d27"
os = "windows"

    [[libstdcxx.download]]
    sha256 = "d07a68e57c06caec86cca0ab25836821f1e40353404ddf35d7485771e61da3ef"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0/libstdcxx-v14.2.0-x86_64-w64-mingw32.tar.gz"
[[libstdcxx]]
arch = "i686"
git-tree-sha1 = "b3f477981b07cb742c4315cc8756578e7d25987d"
os = "windows"

    [[libstdcxx.download]]
    sha256 = "a5935d1ac6b8958a07465ebc15dc0ab3f97aa159b48a07caa7022de2837960b0"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0/libstdcxx-v14.2.0-i686-w64-mingw32.tar.gz"
[[libstdcxx]]
arch = "x86_64"
git-tree-sha1 = "01c6f88a960d132dcdb07561c7c6b27bd1728b97"
os = "macos"

    [[libstdcxx.download]]
    sha256 = "4823b8ae3282af4a87d7552be648b9e766bdbe564764c36f310203db914a3a02"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0/libstdcxx-v14.2.0-x86_64-apple-darwin.tar.gz"
[[libstdcxx]]
arch = "aarch64"
git-tree-sha1 = "45cf4e899ff323ea324a96ec06184fed95e444dd"
os = "macos"

    [[libstdcxx.download]]
    sha256 = "d47f527ba3701836db0366dfa41eeb4983bc135deff0185d796700e8eaf97b4c"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0/libstdcxx-v14.2.0-aarch64-apple-darwin.tar.gz"

[[libstdcxx-build_log]]
arch = "x86_64"
git-tree-sha1 = "c89b8c339af01f404134c7afc83c38dc467ff0fb"
lazy = true
libc = "glibc"
os = "linux"

    [[libstdcxx-build_log.download]]
    sha256 = "8cd7157bef4608937246a291483dadcee47897f266e57778e14762d709ca8627"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0/libstdcxx-build_log-v14.2.0-x86_64-linux-gnu.tar.gz"
[[libstdcxx-build_log]]
arch = "i686"
git-tree-sha1 = "d06e3031f7962b1d6c6db09f4d47ea64778a5a75"
lazy = true
libc = "glibc"
os = "linux"

    [[libstdcxx-build_log.download]]
    sha256 = "ad96470e3855f558396f5e8a6fbb00b27ad5732e67396bf038b52b628c75c8c3"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0/libstdcxx-build_log-v14.2.0-i686-linux-gnu.tar.gz"
[[libstdcxx-build_log]]
arch = "aarch64"
git-tree-sha1 = "5949b0b288546d29229f4ee1a3db3865a0decd02"
lazy = true
libc = "glibc"
os = "linux"

    [[libstdcxx-build_log.download]]
    sha256 = "70b71e8d5639f164859a3cfd4144dab80a47f8ba57c1d6fa7debf01f467bc0c2"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0/libstdcxx-build_log-v14.2.0-aarch64-linux-gnu.tar.gz"
[[libstdcxx-build_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "54a1de7d0650fc93dbd4b7e31082059a7194bd37"
lazy = true
libc = "glibc"
os = "linux"

    [[libstdcxx-build_log.download]]
    sha256 = "5e685381580e9f3e206831ccac7ec2215adb524ef33534a2940d69b1b3e4da0c"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0/libstdcxx-build_log-v14.2.0-armv6l-linux-gnueabihf.tar.gz"
[[libstdcxx-build_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "086c93b532447a4e0134151134b529bec132cf34"
lazy = true
libc = "glibc"
os = "linux"

    [[libstdcxx-build_log.download]]
    sha256 = "a4540a957d862d446bb8517fca4bc10780003ab3e3f5eb580ed27e86015f7aa0"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0/libstdcxx-build_log-v14.2.0-armv7l-linux-gnueabihf.tar.gz"
[[libstdcxx-build_log]]
arch = "powerpc64le"
git-tree-sha1 = "8221c4c8b08ad1d9e4282f9cac1947e593c63721"
lazy = true
libc = "glibc"
os = "linux"

    [[libstdcxx-build_log.download]]
    sha256 = "6a9f82adf7c36c991059db875acc8af720e89c49f31042d5509b75f7401c34b7"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0/libstdcxx-build_log-v14.2.0-powerpc64le-linux-gnu.tar.gz"
[[libstdcxx-build_log]]
arch = "x86_64"
git-tree-sha1 = "a1e02a8c76d87d966c1722cdb8d89fcbba4a6abb"
lazy = true
libc = "musl"
os = "linux"

    [[libstdcxx-build_log.download]]
    sha256 = "649d9b01bfbc89ee82008d4275e29b8b6d58d028c681fd4911efce69742f2235"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0/libstdcxx-build_log-v14.2.0-x86_64-linux-musl.tar.gz"
[[libstdcxx-build_log]]
arch = "i686"
git-tree-sha1 = "5a0ce7a993cfb0189a5cb55453d84b89f10a29c3"
lazy = true
libc = "musl"
os = "linux"

    [[libstdcxx-build_log.download]]
    sha256 = "c89f4431294d4e86733ba0dc1f41b018f7d40c94b74133e65b7ca06d5fa498a9"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0/libstdcxx-build_log-v14.2.0-i686-linux-musl.tar.gz"
[[libstdcxx-build_log]]
arch = "aarch64"
git-tree-sha1 = "a798622a3ad4da369599bc2393c945c8fdfe0b05"
lazy = true
libc = "musl"
os = "linux"

    [[libstdcxx-build_log.download]]
    sha256 = "0b867234eb8a8476b38b435bc1c9147af3aaaf86f190894b52b237bc0c142706"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0/libstdcxx-build_log-v14.2.0-aarch64-linux-musl.tar.gz"
[[libstdcxx-build_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "800e0077e82410fcbcb399307ae3a5e38638bba8"
lazy = true
libc = "musl"
os = "linux"

    [[libstdcxx-build_log.download]]
    sha256 = "c1dfb3358eb4ea3eb28f01dd8857c0419c8948c9eedc0198f171478edd8e878b"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0/libstdcxx-build_log-v14.2.0-armv6l-linux-musleabihf.tar.gz"
[[libstdcxx-build_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d3194acf4c6631667534bc139b9374a974e50c94"
lazy = true
libc = "musl"
os = "linux"

    [[libstdcxx-build_log.download]]
    sha256 = "7677f1a3727fd0c1dd279722d3854da3cf92081a91eb3c932829f70b5e4f3d39"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0/libstdcxx-build_log-v14.2.0-armv7l-linux-musleabihf.tar.gz"
[[libstdcxx-build_log]]
arch = "x86_64"
git-tree-sha1 = "8c9efdf524fae9b78c9ad1330b39ddf7cb665e94"
lazy = true
os = "windows"

    [[libstdcxx-build_log.download]]
    sha256 = "000c6e67549a15df0203c33cde594d50cd059812842f628ffc7a76e1ade5c6a6"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0/libstdcxx-build_log-v14.2.0-x86_64-w64-mingw32.tar.gz"
[[libstdcxx-build_log]]
arch = "i686"
git-tree-sha1 = "e180b9af9020d44312a4fc4322685b9173d085f2"
lazy = true
os = "windows"

    [[libstdcxx-build_log.download]]
    sha256 = "40c86e39050b0449a24438ff5e38cb71390c8c224071cd0f58ede9a96185a09a"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0/libstdcxx-build_log-v14.2.0-i686-w64-mingw32.tar.gz"
[[libstdcxx-build_log]]
arch = "x86_64"
git-tree-sha1 = "63d635f47d85a78e36c3d4f2bad62ab974aeafa0"
lazy = true
os = "macos"

    [[libstdcxx-build_log.download]]
    sha256 = "dacc11423aab90420f008a460e51ae9cc78d193a03b79486e654c1d2ffbe494d"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0/libstdcxx-build_log-v14.2.0-x86_64-apple-darwin.tar.gz"
[[libstdcxx-build_log]]
arch = "aarch64"
git-tree-sha1 = "9561a7ca2fae9cff2c8c8707bb3d10464ac8e5db"
lazy = true
os = "macos"

    [[libstdcxx-build_log.download]]
    sha256 = "e41391f1d76a73888ea454bdc08c72777ab2dc168f881fb9bcfc7bcb2a3431a1"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0/libstdcxx-build_log-v14.2.0-aarch64-apple-darwin.tar.gz"

[[libstdcxx-extract_log]]
arch = "x86_64"
git-tree-sha1 = "c5011967cce87f9d701525551eb6c9f62c207461"
lazy = true
libc = "glibc"
os = "linux"

    [[libstdcxx-extract_log.download]]
    sha256 = "42a8dc4471ae07a7c5e4ee4feb9a06b25ff8066ab56235fb0027af8a48f26dd4"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0/libstdcxx-extract_log-v14.2.0-x86_64-linux-gnu.tar.gz"
[[libstdcxx-extract_log]]
arch = "i686"
git-tree-sha1 = "ae5673a73fafa0ef4e2053cd9c3c76d380ca69e7"
lazy = true
libc = "glibc"
os = "linux"

    [[libstdcxx-extract_log.download]]
    sha256 = "c3132c9cf967c1233730d2a5d825404458224ff52b00c9338d1113b1ea708c35"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0/libstdcxx-extract_log-v14.2.0-i686-linux-gnu.tar.gz"
[[libstdcxx-extract_log]]
arch = "aarch64"
git-tree-sha1 = "70b4ac2badef94667649311e45b24f23d2e8e94e"
lazy = true
libc = "glibc"
os = "linux"

    [[libstdcxx-extract_log.download]]
    sha256 = "67b50b66be5b53f66d772e1edf84a93eb065d1a60f39fea80201537d3a264337"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0/libstdcxx-extract_log-v14.2.0-aarch64-linux-gnu.tar.gz"
[[libstdcxx-extract_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b7ac84683cc9dccb848b0cb895ff95de9fb45d51"
lazy = true
libc = "glibc"
os = "linux"

    [[libstdcxx-extract_log.download]]
    sha256 = "029aef5b55dbe8047ce6b009f09e76f83ab7c7c77b21efaca58152a8b63e687a"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0/libstdcxx-extract_log-v14.2.0-armv6l-linux-gnueabihf.tar.gz"
[[libstdcxx-extract_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7cb40d082e6104f8df101d1b021c065a41a459dd"
lazy = true
libc = "glibc"
os = "linux"

    [[libstdcxx-extract_log.download]]
    sha256 = "80fd18cb26b953f22c2d752c5ef31e04535b28cc3ec0f3042770b39fb3d68a70"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0/libstdcxx-extract_log-v14.2.0-armv7l-linux-gnueabihf.tar.gz"
[[libstdcxx-extract_log]]
arch = "powerpc64le"
git-tree-sha1 = "372846ce5a547256f843201fdfaf9294b33747ac"
lazy = true
libc = "glibc"
os = "linux"

    [[libstdcxx-extract_log.download]]
    sha256 = "159d7130505e304624d3128ecbe9e60c34e4008f3af9e02c2dbd439760d01580"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0/libstdcxx-extract_log-v14.2.0-powerpc64le-linux-gnu.tar.gz"
[[libstdcxx-extract_log]]
arch = "x86_64"
git-tree-sha1 = "286b569da4c2d6bf9ca1a9cb2a2ef3041b68e1e8"
lazy = true
libc = "musl"
os = "linux"

    [[libstdcxx-extract_log.download]]
    sha256 = "ab5ffa4b7990df86f5e24390927fad7c3eaca7a2233bc8eeb9fae3d9612a5eef"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0/libstdcxx-extract_log-v14.2.0-x86_64-linux-musl.tar.gz"
[[libstdcxx-extract_log]]
arch = "i686"
git-tree-sha1 = "01057de3eecd7881841bc3c410e5e83c8079880a"
lazy = true
libc = "musl"
os = "linux"

    [[libstdcxx-extract_log.download]]
    sha256 = "243971c4248a01bcdce092bebbd693bac0ad0738100203ee12f701a09ee808ae"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0/libstdcxx-extract_log-v14.2.0-i686-linux-musl.tar.gz"
[[libstdcxx-extract_log]]
arch = "aarch64"
git-tree-sha1 = "b24d273f77144bfee44f42aa3fb23339e8147e5b"
lazy = true
libc = "musl"
os = "linux"

    [[libstdcxx-extract_log.download]]
    sha256 = "3dedfbbb88f3574d1ea7eb7551d402b65203146c68ce54621c56bab25157efe1"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0/libstdcxx-extract_log-v14.2.0-aarch64-linux-musl.tar.gz"
[[libstdcxx-extract_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b5a8c888a6420127b55c829d57d72605f68de6fd"
lazy = true
libc = "musl"
os = "linux"

    [[libstdcxx-extract_log.download]]
    sha256 = "fad0209592a106c04e66254f56ead86399863f2aa429b821ba7444fc7988a2c8"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0/libstdcxx-extract_log-v14.2.0-armv6l-linux-musleabihf.tar.gz"
[[libstdcxx-extract_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "97e24b556854c7ad694da25ddc2695305bb05256"
lazy = true
libc = "musl"
os = "linux"

    [[libstdcxx-extract_log.download]]
    sha256 = "845297d0ae8ce9567c454bc8e8b9f4aac6b58b2b44768f0ea4a94b93d4377d5f"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0/libstdcxx-extract_log-v14.2.0-armv7l-linux-musleabihf.tar.gz"
[[libstdcxx-extract_log]]
arch = "x86_64"
git-tree-sha1 = "ce2b988defe38b195b32ce1489f8db3e6568b195"
lazy = true
os = "windows"

    [[libstdcxx-extract_log.download]]
    sha256 = "10d5bda7cbd187efa54cb82f3a6798ff0a7f12f7f57dee56df2975f9d5761b7a"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0/libstdcxx-extract_log-v14.2.0-x86_64-w64-mingw32.tar.gz"
[[libstdcxx-extract_log]]
arch = "i686"
git-tree-sha1 = "a47ac32f771949fa29f1b284d773878c0ed74d27"
lazy = true
os = "windows"

    [[libstdcxx-extract_log.download]]
    sha256 = "395a9a22e986e8b577746319619e2aa4f49417e282c41e829e4c44df714ba04d"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0/libstdcxx-extract_log-v14.2.0-i686-w64-mingw32.tar.gz"
[[libstdcxx-extract_log]]
arch = "x86_64"
git-tree-sha1 = "e83677ccadb4571adb409406a9112e4f5bbf365a"
lazy = true
os = "macos"

    [[libstdcxx-extract_log.download]]
    sha256 = "01422a821228e8c193ee280a07c8c32df118bb69960c9adbe85a59aadd8044d9"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0/libstdcxx-extract_log-v14.2.0-x86_64-apple-darwin.tar.gz"
[[libstdcxx-extract_log]]
arch = "aarch64"
git-tree-sha1 = "e66bfbe5b7e46300f97ad6880bae15660da24ce8"
lazy = true
os = "macos"

    [[libstdcxx-extract_log.download]]
    sha256 = "92afb47a432c9f91943882aa2e97cd5f09b4ca616307c4696b1b4502e18acc01"
    url = "https://github.com/staticfloat/libstdcxx_jll.jl/releases/download/v14.2.0/libstdcxx-extract_log-v14.2.0-aarch64-apple-darwin.tar.gz"
